### ISSUE TITLE
GET https://localhost:5001/_content/BlazorMedia/BlazorMedia.js net::ERR_ABORTED 404

### ISSUE THREAD

**Issue by drma-tech** [Mercurial/BlazorMedia#17]
![image](https://user-images.githubusercontent.com/12803050/107859346-a830b680-6e17-11eb-9b38-6e034287e8fa.png)

**Comment by isozworld** [comment]
You should put this `    <script type="text/javascript" src="_content/BlazorMedia/BlazorMedia.js"></script>` code inside index.html

**Comment by drma-tech** [comment]
could have this in the documentation

**Comment by isozworld** [comment]
this is actually about Blazor structure.
