### ISSUE TITLE
Take Photo using VideoMedia Control

### ISSUE THREAD

**Issue by manthena** [Mercurial/BlazorMedia#7]
Hi @Mercurial, this is really a wonderful control .... much needed in the Blazor world.

The control itself is working fine for streaming of video data. However my requirement is to take a photo from webcam upon clicking a button. Here is my code ....

```
<VideoMedia @ref="CameraControl" Width="480" Height="270" RecordAudio="false"></VideoMedia>
<br />
<button @onclick="@TakePhoto">Take Photo</button>

@code {

    public VideoMedia CameraControl { get; set; }

    protected async Task TakePhoto()
    {
        //CameraControl.ReceiveData();
    }
}
```
I see the control has a ReceiveData() method, however it needs an input of int array. Can you please suggest on how do I capture the photo using this control?

**Comment by Mercurial** [comment]
I appreciate the feedback, I'll get back to you on this as soon as possible.

**Comment by Mercurial** [comment]
hi @manthena I pushed a major cleanup update and some new functionalities included taking photos / still images.

You should be able to find sample code in the Demo project

I also pushed a nuget package update

cb38d414a834de826838d1f6af917c9cf773c492

**Comment by manthena** [comment]
Thank you @Mercurial , it worked like a charm. This has simplified our project migration to Blazor. Really appreciate your help and contribution 👍

**Comment by Mercurial** [comment]
> Thank you @Mercurial , it worked like a charm. This has simplified our project migration to Blazor. Really appreciate your help and contribution 👍

Just genuinely happy I could help some fellow dev out :D
